### ISSUE TITLE
Error loading monaco-editor

### ISSUE THREAD

**Issue by mauringhio** [SamVerschueren/ngx-monaco#12]
Hi, I get the following error when the app tries loading the monaco-editor, it must be a problem in the way the monaco lib is loaded in MonacoEditorService :
Refused to execute script from 'http://localhost:9000/libs/vs/loader.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by SamVerschueren** [comment]
Have you added this to the `angular-cli.json` file? https://github.com/SamVerschueren/ngx-monaco/blob/master/readme.md#angular-clijson

**Comment by mauringhio** [comment]
I have double checked that and still the same error

**Comment by SamVerschueren** [comment]
It looks like it can't find the files and serves the index.html page. Can you double check if the file is on that specific location?

**Comment by mauringhio** [comment]
Ok, I've copied manually the lib to the target/www folder and it works, 
I think it's due to my project architecture for development using spring-boot and yarn webpack .
I apologize for opening this ticket, many thanks for your help.
