### ISSUE TITLE
Any plans to support it for Angular 7?

### ISSUE THREAD

**Issue by kent08ian** [SamVerschueren/ngx-monaco#19]

**Comment by SamVerschueren** [comment]
I don't see why it wouldn't work. Did you test it?

**Comment by kent08ian** [comment]
![image](https://user-images.githubusercontent.com/7494219/48006944-7ff28180-e151-11e8-8da4-4233f180b10d.png)

I'm getting this error :|

**Comment by kent08ian** [comment]
Sorry for the disturbance. I managed to work it on my local development. Thank you by the way.

**Comment by makulis** [comment]
I'm getting the same error. Can you please explain what you did? Thanks.
