### ISSUE TITLE
editor content not changing with this.file.content="xxx" 2nd time

### ISSUE THREAD

**Issue by moorthi07** [SamVerschueren/ngx-monaco#9]
The initial file.content binding does not work when you change the file.content again.  Or editor is not refreshing if you change the file.content in the code.

**Comment by SamVerschueren** [comment]
Can you provide some code?

Do you mean something like this?

```ts
import { Component, OnInit } from '@angular/core';
import { MonacoFile } from 'ngx-monaco';

@Component({
	selector: 'app-root',
	styles: ['monaco-editor { height: 500px; }'],
	template: `
		<monaco-editor
			theme="vs-dark"
			[file]="file"
			(fileChange)="onFileChange($event)">
		</monaco-editor>
	`
})
export class AppComponent {
	file: MonacoFile = {
		uri: 'index.js',
		language: 'javascript',
		content: `console.log('hello world');`
	};

	ngOnInit() {
		this.file.content = `const foo = 'bar';`
	}
}
```

No, that does not work. That's how Angular works, it's using immutable objects. In order for this to work, you would have to provide a new object. Otherwise the change detection wouldn't be performant as it has to observe every key of all input objects.

```ts
import { Component, OnInit } from '@angular/core';
import { MonacoFile } from 'ngx-monaco';

@Component({
	selector: 'app-root',
	styles: ['monaco-editor { height: 500px; }'],
	template: `
		<monaco-editor
			theme="vs-dark"
			[file]="file"
			(fileChange)="onFileChange($event)">
		</monaco-editor>
	`
})
export class AppComponent {
	file: MonacoFile = {
		uri: 'index.js',
		language: 'javascript',
		content: `console.log('hello world');`
	};

	ngOnInit() {
		this.file = {
			...this.file,
			content: `const foo = 'bar';`
		};
	}
}
```

**Comment by moorthi07** [comment]
I'm trying to reset the content onClick of the 'reset button'
onClick(){
 this.file= {
      uri: 'index.js',
      language: 'json',
      content: `{}`
    };
} 

This not working.

**Comment by SamVerschueren** [comment]
I'll look into it tomorrow, thanks for reporting.

**Comment by moorthi07** [comment]
Hi, I'm in a hurry to get it done today. can you help. Her is a link you can modify and create an example

**Comment by moorthi07** [comment]
pl. put the example what you are suggesting is working.

**Comment by SamVerschueren** [comment]
Sorry, don't have access to my computer anymore today. It's already late here. Feel free to debug this yourself and send a PR.

**Comment by moorthi07** [comment]
I'm expecting the directive to work like this example
http://plnkr.co/edit/K7dmQotHNfbXiQLOlvDO?p=info

**Comment by SamVerschueren** [comment]
Yes, it doesn't work on Stackblitz because you can't provide [`assets`](https://github.com/SamVerschueren/ngx-monaco#angular-clijson) to your `.angular-cli.json`.

I found the cause of this issue. A fix is on the way.

**Comment by SamVerschueren** [comment]
`ngx-monaco@0.6.1` released. Install that version and updating the file like you did previously should work now.

```js
this.file= {
      uri: 'index.js',
      language: 'json',
      content: `{}`
};
```

**Comment by moorthi07** [comment]
Wrong fix. You should have tested before you closed.  Here is the problem. 
Yes , it replaces new content.
But 'EDITOR BECAME UNEDITABLE' . Cursor always goes to the top left corner.  :(

**Comment by SamVerschueren** [comment]
Instead of getting angry at me, try to help me instead... I'm maintaining this in my SPARE time.

It worked in my test setup, I'll take another look at it tomorrow.

**Comment by moorthi07** [comment]
oops,  sorry it sounded like angry :). Just giving you the result . I'm trying monaco work with ng, I'll keep you posted. Thanks.

**Comment by SamVerschueren** [comment]
Tested it with the latest version and it works. Here's a screen capture. Do you get errors in your console or something? Feel free to capture the behaviour so I can take a better look.

<img width="824" alt="screen shot 2018-01-20 at 13 52 01" src="https://user-images.githubusercontent.com/1913805/35183607-6706fe0e-fde9-11e7-90fc-3d3946302434.png">

**Comment by moorthi07** [comment]
is it working with ngx-monaco@0.6.1 or prev? My cursors jumping back to line 1,1 position.

**Comment by SamVerschueren** [comment]
`0.6.1`. I'll try your example when I find some time.

**Comment by SamVerschueren** [comment]
I have no clue of what's going on in your project, but this just works. Have you opened the Chrome DevTools to see if an error appears in the console?

```ts
ngOnInit() {
	this.file = {
		uri: 'index.js',
		language: 'json',
		content: '{"foo": "bar"}'
	};
}

reset() {
	this.file = {
		uri: 'index.js',
		language: 'json',
		content: `{""}`
	};
}
```

**Comment by moorthi07** [comment]
in ng 4?

**Comment by SamVerschueren** [comment]
Tested it in 5, I'll take a look if it works in 4 as well. Do you have any errors in chrome devtools?

**Comment by moorthi07** [comment]
problem is, its not throwing any console error
